package com.interview.common.saga;

public enum SagaEventType {
    PAYMENT_DEDUCTED,
    PAYMENT_DEDUCT_FAILED,
    PAYMENT_REFUNDED,
    PAYMENT_REFUND_FAILED,
    INVENTORY_RESERVED,
    INVENTORY_RESERVE_FAILED,
    INVENTORY_RELEASED,
    INVENTORY_RELEASE_FAILED,
    MERCHANT_CREDITED,
    MERCHANT_CREDIT_FAILED,
    MERCHANT_DEBITED,
    MERCHANT_DEBIT_FAILED
}
